name: test, publish

on:
  - push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.docker
      # -
      #   name: test
      #   env:
      #     PACKAGE: MarkdownLink
      #   run: docker run --rm -it -e PACKAGE=$PACKAGE -v $PWD:/home/docker/project unittesting
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: contains(github.ref, 'master')
  #   steps:
  #     -
  #       uses: docker://node:12
  #     -
  #       name: publish
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: npm run release
