name: test, publish
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: ./
      -
        name: test
        run: sh test.sh
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'master')
    steps:
      -
        uses: docker://node:12
      -
        name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
